# Setup
title:               Journey
tagline:             'keep notes'
description:         
url:                 http://yulii77.github.io/tagebuch
baseurl:             ''
paginate:            5
permalink:           

# About/contact
author:
  name:              Lily Yu
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
